### ISSUE TITLE
ResNet-32 or ResNet-32 with channel x4 (Cifar100-lt)

### ISSUE THREAD

**Issue by CVHvn** [fistyee/MDCS#1]
Is this Cifar 100-lt result from ResNet-32 (with inplanes (base feature) of 16) or ResNet-32 with channels multiplied by 4 (with inplanes of 16 x 4 = 64)?

**Comment by fistyee** [comment]
Thank you for your attention. For Cifar 100-lt, the ResNet-32 is with inplanes of 16.
